import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "@/styles/css/styles.css";

import { Montserrat } from "next/font/google";
const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat", display: "swap" }); // Specify subsets if needed

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <div className="page">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
